# Generated by Django 5.0 on 2024-06-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0004_alter_tema_dostupnost_delete_dostupnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostupnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Dostupnosť',
                'verbose_name_plural': 'Dostupnosť',
            },
        ),
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.dostupnost'),
        ),
    ]
