# Generated by Django 5.0 on 2024-06-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0005_dostupnost_alter_tema_dostupnost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odbor',
            options={'verbose_name': 'Odbor', 'verbose_name_plural': 'Odbory'},
        ),
    ]
