# Generated by Django 5.0 on 2024-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0006_alter_odbor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='pocet_konzultacii',
            field=models.IntegerField(default=0),
        ),
    ]
